### ISSUE TITLE
Addinng CODE_OF_CONDUCT

### ISSUE THREAD

**Issue by nisha331** [amanosan/Discord-Bot#1]
As there is no code of conduct file I would like to add it.
I as a participant of LGMSOC would like to work on it kindly assign it to me

**Comment by PaliwalUmesh** [comment]
@nisha331 try to add mention so that the owner of project can get notification about your comment , like i mentioned you.
It will help you to increase your chances to become an assignee.

**Comment by nisha331** [comment]
Thanks @PaliwalRP for saying this.
@amanosan As there is no code of conduct file I would like to add it.
I as a participant of LGMSOC would like to work on it kindly assign it to me

**Comment by amanosan** [comment]
Sure you can add the Code of Conduct File.

**Comment by Salonee-Jain** [comment]
Can I work on this issue under LGM SOC

**Comment by amanosan** [comment]
The Code of Conduct File has already made by Nisha, you can suggest updates/changes if you want.
